### ISSUE TITLE
Port to MicroPython

### ISSUE THREAD

**Issue by cwalther** [pewpew-game/pewpew#10]
At [cwalther/pewpew:master-micropy](https://github.com/cwalther/pewpew/compare/master-micropy), I have ported the PewPewLite4.0 library and the games from CircuitPython to MicroPython. I am not asking that this be integrated into the main repository, so this is not a pull request (though I wouldn’t oppose either). I merely want to bring it to the attention of people who might have a use for it. I mainly did it for myself, for the following reasons:
- I was getting weird errors with one complex program and wanted to check if they also occur with MicroPython (they don’t).
- I wanted to play with asyncio, which is not available on CircuitPython yet.
- I needed umqtt, which is not built-in on CircuitPython and does not run without adjustments.

Main differences that required porting are
- `time` API: `monotonic()` is unavailable, and integer milliseconds are preferred over floating-point seconds.
- `machine.I2C.writeto()` has no `end` argument, which requires a separate 1-byte buffer.

Tested on ESP8266 (Adafruit Feather HUZZAH). I don’t even know if there are any other Feather boards that run MicroPython. If so, I’m not sure if the I2C pin assignments are universal. Contributions welcome.

**Comment by deshipu** [comment]
This is awesome! I definitely want to have a MicroPython version, especially since there is also an ESP32 Feather that doesn't have CircuitPython support at all. I will look in the morning and try to integrate it with the current repository structure somehow.

**Comment by deshipu** [comment]
By the way, it would be interesting to see the program that is giving you the problems.

**Comment by cwalther** [comment]
Cool! Options for integrating it could be
- A separate branch that mirrors everything, as I did here. That makes it easy to compare the two versions and keep them synchronized, but is maybe a little less discoverable.
- Separate subdirectories under _libs/_. That requires that everything outside of that runs on both, which makes the code a little larger. This is already achieved for the two games included here, which fortunately only required catching ImportErrors (_frog.py_ even works unmodified), and I also have it working for the menu module from #9, but there it adds a few more lines to abstract the `time` API differences.

I didn’t know about the ESP32 Feather not having CircuitPython. By the way, have you talked to the https://www.oxocard.ch guys at Maker Faire Zürich? It has an 8x8 screen, six buttons, and an ESP32 running MicroPython – perfect platform to run PewPew on! 😀 I didn’t buy one because I had already bought the first (ATmega) version a year ago and never did anything with it.

The problematic program was a WIP experiment that I didn’t plan to publish (yet), but I’ll think about it. The symptom was that I occasionally got exceptions because some variables were `None` or some object attributes were missing that could not possibly be `None` or missing according to my code. Very strange. The program was so large (about 6 KB) that it didn’t compile on the device anymore, I had to precompile it, and it made excessive use of generators for animation – I suspect it was either of these that caused the problem. But I never tried to get a minimal reproducing example and make a proper bug report.

**Comment by deshipu** [comment]
I need to reorganize the repositories a little, than every platform can get its own repository, forked from the same common parent, so that it will be easy to do comparisons and pulls between them. I think that is the only sane approach. Unfortunately, I'm right now pretty busy with the Hacakday Prize stuff (deadline on Monday) and then the PyCon.de (until the end of the week). Hopefully I can work on this after that.

I really want to have all the ports code-compatible, so that there is no modification of programs necessary. If that means including additional modules just because the original had them called differently, so be it. I will work on that once it's in its own repo.

I talked to the oxocard people briefly, but I didn't really show them PewPew. I think they are going in a slightly different direction than me, and that it's not a compatible platform from the point of view of controls (no d-pad, etc.).

**Comment by cwalther** [comment]
No hurry from my part. Good luck with the Hackaday Prize and enjoy PyCon!

By “include additional modules”, do you mean that the MicroPython port would include e.g. a `time` module that offers `monotonic()` and a `random` module aliasing `urandom`, so that the existing games in this repository would work unmodified? But other existing games written for CircuitPython could be using all kinds of CircuitPython APIs that are not available in MicroPython, so where would you stop? I see no better solution here than to leave it up to the game author to make their game run on both, if they want it to be cross-platform.

**Comment by deshipu** [comment]
Well, I would limit it to the modules that are built into CircuitPython and are not for interacting with hardware  (which would open a completely new can of worms). For now I'm thinking about `time`, `random` and `microcontroller` (for resetting the board).

**Comment by deshipu** [comment]
I just went ahead and created the separate repositories for different version of the pew library. I can also create one for MicroPython now, if you are still interested?

**Comment by cwalther** [comment]
Sure! It seems like the choice between CircuitPython and MicroPython is partly orthogonal to the choice of platform, so at this point there would be pew-pewpewlite-4.x-micropython and pew-d1mini-micropython? (I can’t contribute the latter because I don’t currently have a PewPew D1 Mini. But then it looks a bit unmaintained, comparing it to pewpewlite-4.x I can spot several bugs that indicate nobody has been using it.)

I always find it a bit of a shame when repository reorganizations lose the existing history, but maybe in this case it wasn’t worth the effort.

**Comment by deshipu** [comment]
The d1mini already uses MicroPython, actually. It's for an early prototype that I made using it, which I kept because I have given a few units to some people. Indeed it is not maintained.

I could have kept the history by cloning the repository and just removing all the other files, and maybe stripping the history of those files as well, but it's more work than I have time for right now. The original repository is still there, so the history is not completely lost.

I will create ``pew-pewpewlite-4.x-micropython`` then.

**Comment by cwalther** [comment]
I have pushed my stuff there. I noticed that the pew-* repositories are not forks of each other, which seems to mean that GitHub cannot compare between them, do you think that’s a problem?

**Comment by deshipu** [comment]
Thank you. I can't fork a repository to the same account, so I have no idea how I would make them forks for github. In any case, git lets you do operations on unrelated repositories anyways, so it should all be good.

**Comment by deshipu** [comment]
You probably want to edit the license file to include yourself in it.

**Comment by cwalther** [comment]
> I can't fork a repository to the same account

Hmm, you’re right. Weird. That seems like a completely needless restriction.

> You probably want to edit the license file to include yourself in it.

I didn’t do that because in this case I consider my contributions minor enough that I’m fine with assigning copyright to you. But if you prefer to have all contributors mentioned, sure, I can do that.

**Comment by deshipu** [comment]
> But if you prefer to have all contributors mentioned, sure, I can do that.

I think it's only fair.

**Comment by cwalther** [comment]
I think we’re done here. Thanks!
