### ISSUE TITLE
Othello game

### ISSUE THREAD

**Issue by cwalther** [pewpew-game/pewpew#12]
Since you have expressed interest in adding my Othello game: I have a version that I consider ready for a 1.0 release now. It is at [cwalther/pewpew-game-othello](https://github.com/cwalther/pewpew-game-othello) and you are welcome to make a _game-othello_ repository and push it there.

Compared to the last version you have seen, this one
- has optimized weights, so it plays slightly better
- detects when the game is over and shows who has won with an animation
- swaps colors on the PewPew 10.x to make them better distinguishable on the monochrome display.

**Comment by deshipu** [comment]
Thank you, I forked it to this organization.

**Comment by cwalther** [comment]
Thanks!
