### ISSUE TITLE
How to contribute documentation translations?

### ISSUE THREAD

**Issue by das-g** [pewpew-game/pewpew#18]
For a workshop with Swiss pupils, who might not yet know English well enough to follow technical instructions in English, I'd like to translate at least the [bouncing ball tutorial](https://pewpew.readthedocs.io/en/latest/tutorial.html), probably also the [sokoban tutorial](https://pewpew.readthedocs.io/en/latest/tutorial-sokoban.html) and maybe even the complete PewPew documentation to German.

It probably would make sense for the results to show up https://pewpew.readthedocs.io/de and that German could be chosen in the documentation-version menu* for pages that have been translated.

*(This one: ![image](https://user-images.githubusercontent.com/97746/68693238-3401c600-0577-11ea-8242-ad7244af861d.png))

Where in the repo should I place the translated files to achieve that?

It would also probably make sense, that others can collaborate on the translations and that the same workflow is used for all target languages. For that, it'd be good to use a translation collaboration platform like Transifex or Crowdin. Is there any preference on which platform should be used for the PewPew documentation?

**Comment by das-g** [comment]
I guess a workflow as suggested by https://www.sphinx-doc.org/en/master/usage/advanced/intl.html could work, but I'm unsure which files should be committed to the Git repository, and at what stage.

**Comment by deshipu** [comment]
I'm sorry, I didn't see this issue. I know that @cwalther has already translated some of the PewPew documentation to German. I will make a clone of the repository with the docs, so that you can translate it.

**Comment by deshipu** [comment]
I have created the ReadTheDocs project here: https://pewpew-german.readthedocs.io/
The repository is here: https://github.com/pewpew-game/pewpew-docs-de

Let me know your login at ReadTheDocs, then I can give you access to the settings.

**Comment by das-g** [comment]
> Let me know your login at ReadTheDocs, then I can give you access to the settings.

I didn't have an account there yet, so I've created one now: [das-g](https://readthedocs.org/profiles/das-g/)

**Comment by das-g** [comment]
> I have created the ReadTheDocs project here: https://pewpew-german.readthedocs.io/
> The repository is here: https://github.com/pewpew-game/pewpew-docs-de

That's a clone of https://github.com/pewpew-game/pewpew (+ commit https://github.com/pewpew-game/pewpew-docs-de/commit/d431d149ee5e042ca50e6c3f9306438db11bc358 to remove everything but the documentation), not a clone of @cwalther's existing translation, is it?

@cwalther, are your translations of (parts of) the PewPew documentation already available somewhere and if not, would you be willing to make them available?

**Comment by cwalther** [comment]
I just pushed it here: https://github.com/cwalther/pewpew/commits/reference-de
It’s just that one commit 935bc91. I’ll look at what you’re doing later, until tomorrow I’m busy.

**Comment by das-g** [comment]
@deshipu Are you OK with me creating a Transifex organization for PewPew?

**Comment by deshipu** [comment]
I don't see why not, as long as I don't have to pay for it.

**Comment by deshipu** [comment]
However, I don't think transifex will give you something. CircuitPython itself already has German translation, you only need the documentation, and that's in text files, not gettext-like strings.

**Comment by deshipu** [comment]
The way I usually do this is just translate and commit the text files, and then once in a while rebase with the original repository, to get any changes (they will show up as conflicts) and translate those.

I think we are set up now, so I'm going to close this issue.

**Comment by das-g** [comment]
> I don't see why not, as long as I don't have to pay for it.

I assume PewPew would qualify as an OpenSource not-for-profit project for which they offer free plans.

> However, I don't think transifex will give you something. CircuitPython itself already has German translation, you only need the documentation, and that's in text files, not gettext-like strings.
>
> The way I usually do this is just translate and commit the text files, and then once in a while rebase with the original repository, to get any changes (they will show up as conflicts) and translate those.

The advantage of using a translation platform like Transifex or Crowdin even for prose is that during initial translation we can more easily see how much of the original has already be translated and what parts still need translation. This allows different phrases in the same document to be translated by different people without getting a giant mess, thus enabling us to split up the work.

Also, they enables us to have several translation suggestions for each phrase, without having to (ab)use the PR mechanism for choosing between them.

Further, I hope they enable people to update the translations who are not (yet) confident enough with Git to resolve merge conflicts. And again, if the documentations has multiple changed phrases, this allows to split up the work of updating them without having to leave Git conflict markers or similar inelegant stuff in committed documents.

The downside off course it that they're another tool to operate, and one I yet have to learn. (I know both platforms from the translators' perspective, but haven't yet managed own projects in them.)

> I think we are set up now, so I'm going to close this issue.

:+1:

**Comment by das-g** [comment]
Update: Translation has started at https://www.transifex.com/pew-pew/pew-pew/

To generate upload the strings to be translated, I roughly followed https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#using-transifex-service-for-team-translation. The steps are documented at [`pewpew-game/pewpew-docs-de` branch `german-translation-preparation`](https://github.com/pewpew-game/pewpew-docs-de/commits/german-translation-preparation) except for the `tx push -s` at the end, which doesn't have local effect.

If anyone wants to participate in translating or reviewing translations, please use the "Join team" button on the Transifex project.
