### ISSUE TITLE
Disabling tick()’s catch-up behavior

### ISSUE THREAD

**Issue by cwalther** [pewpew-game/pewpew#5]
The `pew.tick(delay)` function currently acts like “Add a tick on the time scale _delay_ after the last one, and if that’s in the future, wait for it. The first tick is always at the time `pew.init()` was called.”. This has the effect of striving for the desired average frame rate on the long run: when several frames have taken longer than _delay_, or one frame has taken several times _delay_, so that the ticks have slipped into the past, it accelerates the frame rate by making `tick()` return immediately as many times as needed to catch up to the desired overall number of frames.

Usually this is useful, desirable behavior. There are cases where it is not, however: when deliberately running a long computation during which no user input or regular screen updates are needed, then resuming regular updates. Specifically, I am writing a player-vs.-computer Othello game: When it is the player’s turn, regular keyboard/screen updates are needed to move a cursor on the board. `tick` is used to get a constant update rate during that time. When it’s the computer’s turn and the AI is thinking, user input should be ignored and no screen updates are needed. `tick` is not called for several seconds during this time. With the current implementation, this means that when the AI is done thinking and control returns to the player, the catch-up behavior kicks in and the cursor blinks and moves very fast for a few seconds, then settles down to its normal rate. I would like to avoid this and somehow tell the library that the thinking time was spent deliberately and it should not try to catch up with the frames it “missed” during that time.

I could do that by measuring how long the long-running computation took and passing that as the argument to the next `tick`, but that feels like a complicated, dirty workaround. This can be solved more cleanly inside the library.

One way of achieving this that I can think of is to
1. modify the `tick` function to act like “Add a tick on the time scale _delay_ after the last one, and if that’s in the future, wait for it. If there is no last tick, add one now (and don’t wait, since _now_ is not in the future).”
2. add a “reset“ function to “clear all existing ticks” (I call it `tock` but I don’t insist on that name).

The game would then call `tock()` before or after the long-running operation, so that the first `tick(delay)` after resuming regular updates would start a new sequence of regular ticks. Specified as above, that first `tick` would not wait. One could also argue that it should wait for _delay_. But depending on how much CPU time computing a frame takes, both may be equally wrong, and waiting for zero seems like the lesser evil to me.

The implementation could look like this:
```python
def tick(delay):
    global _tick
    if _tick is None:
        _tick = time.monotonic()
    else:
        _tick += delay
        time.sleep(max(0, _tick - time.monotonic()))

def tock():
    global _tick
    _tick = None
```

Rather than by a separate `tock` function, the “reset” behavior could also be triggered by a special argument to `tick`, such as `tick()` or `tick(-1)` or `tick(delay, reset=True)`.

Alternatively, one could specify that `tick` should catch up at most once, i.e. the backlog of “missed“ frames would be clamped to one, by never setting new ticks in the past. That would however lose the property of keeping to a long-term average frame rate.

Rather than submit any of this as a pull request right away, I would like to discuss it first. Do you agree that this is a problem? One that is worth spending some bytes of library code on? Can you think of any better solution?

**Comment by deshipu** [comment]
Hi, I'm sorry that I will be brief, I will give you better replies tomorrow (and to your pull requests too). I really appreciate you taking the time to work on this, and doing such deep analysis. I'm afraid you are assuming more foresight on my part than I deserve — that behavior of the `tick()` function is pretty much accidental, it was simply easy to write it that way. I think that once you skip more than one frame, all bets are off. Most likely then your update code is slower than the desired framerate, and it will only get worse with time. I think the sanest thing to do is to only allow it to skip one frame, and not let the error accumulate. That would be the least surprising behavior, and the most useful for such simple games — at least for the use cases that I can imagine. And if your game has some special needs, you can always write your own tick function — it's there only for convenience after all. What do you think?

**Comment by cwalther** [comment]
You’re right, now that I think about it a bit more, the usefulness of a constant long-term frame rate is marginal for typical PewPew games. The example I subconsciously had in mind involved physics simulation in a multiplayer online game, which is probably not something beginners are going to do here. :) So, an implementation of the behavior you suggest could be
```python
def tick(delay):
    global _tick
    now = time.monotonic()
    _tick = max(_tick + delay, now)
    time.sleep(max(0, _tick - now))
```
and that works fine for my purpose.

**Comment by deshipu** [comment]
Do you want to make a pull request, or should I do it?
