### ISSUE TITLE
Possible typo on the `menu.py`

### ISSUE THREAD

**Issue by yeyeto2788** [pewpew-game/pewpew#7]
Hello! 

there might be an error on the code in the `menu.py`, is there any reason why the `pew` is initialized twice?

On the code in lines 77 and 78 there is the following code:
```
pew.init()
pew.init()
```

Best regards.
P.D: If it's needed just let me know and I can do a PR with the change.

**Comment by deshipu** [comment]
That was a workaround for a bug in the CircuitPython firmware. I should probably remove it now, that we use newer firmware.

**Comment by cwalther** [comment]
Heh, I was wondering about that too, but was too lazy to ask.

**Comment by deshipu** [comment]
This is now fixed in https://github.com/pewpew-game/game-menu/commit/c26ffcfc837a563be540c497899bb14b3e1a26d2

Thank you.
